# Generated by Django 3.1.2 on 2020-10-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=2)),
                ('period', models.IntegerField(default=0)),
                ('group', models.IntegerField(default=0)),
                ('atomic_mass', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=2)),
                ('native_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChemElementAltName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_name', models.CharField(max_length=200)),
                ('chem_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodictable.chemelement')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodictable.language')),
            ],
        ),
    ]
