# Generated by Django 3.1.2 on 2020-10-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodictable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemelement',
            name='num_electrons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chemelement',
            name='num_neutrons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chemelement',
            name='num_protons',
            field=models.IntegerField(default=0),
        ),
    ]
