# Generated by Django 3.1.2 on 2020-10-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodictable', '0002_auto_20201021_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemelement',
            name='name_etymology',
            field=models.TextField(default=''),
        ),
    ]
