# Generated by Django 3.1.2 on 2020-10-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodictable', '0003_chemelement_name_etymology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemelement',
            name='atomic_mass',
        ),
        migrations.RemoveField(
            model_name='chemelement',
            name='name_etymology',
        ),
        migrations.RemoveField(
            model_name='chemelement',
            name='num_electrons',
        ),
        migrations.RemoveField(
            model_name='chemelement',
            name='num_neutrons',
        ),
        migrations.RemoveField(
            model_name='chemelement',
            name='num_protons',
        ),
        migrations.AddField(
            model_name='chemelement',
            name='elem_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chemelement',
            name='phase',
            field=models.CharField(default='', max_length=100),
        ),
    ]
