# Generated by Django 3.1.2 on 2020-10-22 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodictable', '0004_auto_20201022_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemelement',
            name='symbol',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='chemelementaltname',
            name='chem_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodictable.chemelement', to_field='symbol'),
        ),
        migrations.AlterField(
            model_name='chemelementaltname',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodictable.language', to_field='native_name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='native_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
