# Generated by Django 3.1.2 on 2020-10-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodictable', '0005_auto_20201022_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemelementaltname',
            name='chem_element',
        ),
    ]
