# Generated by Django 3.1.2 on 2020-10-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodictable', '0006_remove_chemelementaltname_chem_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemelement',
            name='de_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chemelement',
            name='en_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chemelement',
            name='es_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chemelement',
            name='fr_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chemelement',
            name='it_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chemelement',
            name='pt_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='ChemElementAltName',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
